Features/HDB 56 rnbw not displaying vesting page
HaloDAO/halodao-interface pull request #148
Opened 2022-02-09 05:55 UTC by bill-ov

… while on Vesting page

## Description of Changes

Fix not updating RNBW and xRNBW balance on Vesting page when logged in metamask account while on Vesting page

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDB-56)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
* [ ] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

2022-02-10 07:35 UTC, schystz reviewed
Tested this on preview site, fix looks good! Just 1 comment to maintain backwards compatibility.

2022-02-10 07:35 UTC, schystz commented on src/sushi-hooks/queries/useTokenBalance.ts
> +    setTargetAddress(account)
I think we still need this condition here (see l20) when assigning the targetAddress. We need to make it backwards compatible for others using `useTokenBalance()` hook which explicitly provides an `accountAddress` param

```suggestion
    setTargetAddress(accountAddress ?? account)
```

2022-02-15 01:33 UTC, tracyarciaga approved these changes
Approve this on my end, code looks fine and tested working, but pls resolve @schystz 's comments first.

2022-02-15 03:36 UTC, bill-ov commented on src/sushi-hooks/queries/useTokenBalance.ts
> +    setTargetAddress(account)
@schystz done resolving your feedback

2022-02-15 05:58 UTC, schystz commented on src/sushi-hooks/queries/useTokenBalance.ts
> +  const [targetAddress, setTargetAddress] = useState(account)
@bill-ov I only mentioned this line to use as basis for my comment on line 40. Let's keep the original logic here pls

```suggestion
  const [targetAddress, setTargetAddress] = useState(accountAddress ?? account)
```

2022-02-28 04:59 UTC, bill-ov commented on src/sushi-hooks/queries/useTokenBalance.ts
> +  const [targetAddress, setTargetAddress] = useState(account)
Okay James. I'll change it after lunch. Sorry for not noticing your comment early

2022-02-28 05:15 UTC, bill-ov commented on src/sushi-hooks/queries/useTokenBalance.ts
> +  const [targetAddress, setTargetAddress] = useState(account)
Done changing it James

2022-02-28 05:18 UTC, schystz commented on src/sushi-hooks/queries/useTokenBalance.ts
> +  const [targetAddress, setTargetAddress] = useState(account)
Thanks @bill-ov ! However the linters & unit tests seems to be failing now. Can you pls take care of this? No need to do it now, but will leave it up to you. Not a priority

2022-02-28 05:26 UTC, 0xAplki requested changes
Please check error in github actions. there seemed to be an error in installing dependencies. it's related to the yarn lock committed here

2022-03-01 03:40 UTC, bill-ov commented on src/sushi-hooks/queries/useTokenBalance.ts
> +  const [targetAddress, setTargetAddress] = useState(account)
Hi @schystz. Done resolving the issue. All tests are now passed

2022-03-01 03:43 UTC, schystz approved these changes

2022-03-01 03:43 UTC, merged