Feature/hdf 13 APY
HaloDAO/halodao-interface pull request #15
Opened 2021-06-04 08:48 UTC by barryhalo

## Description of Changes
- APY calculation [Formula](https://halodao.atlassian.net/browse/HDF-13?focusedCommentId=11733)
- Currently using ETH price
- apy = (monthlyInterest * 100) * 12
- Unit tests will be on new task/branch
- Still need some refactoring

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-13)

### Todos:
- Coingecko Halo price as dummy price

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
* [x] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

2021-06-04 08:51 UTC, barryhalo commented on src/components/Farm/FarmPoolCard.tsx
> +  const monthlyAPY = rewardMonthUSDValue / poolLiquidity;
@ctverceles should I rename `monthlyAPY` to `monthlyInterest` since this is not in percentage?

2021-06-07 08:46 UTC, tracyarciaga reviewed
@barryhalo can we format this APY column to include a comma? (same goes for the APY displayed in the vesting page)

![image](https://user-images.githubusercontent.com/6169194/120986940-ad8f8380-c7af-11eb-9186-cbfe10b37e93.png)

2021-06-07 09:37 UTC, tracyarciaga reviewed
@barryhalo can we format this APY column to include a comma? (same goes for the APY displayed in the vesting page)

So far, code looks correct based on Chris' computation.

![image](https://user-images.githubusercontent.com/6169194/120986940-ad8f8380-c7af-11eb-9186-cbfe10b37e93.png)

2021-06-07 10:10 UTC, barryhalo commented
> @barryhalo can we format this APY column to include a comma? (same goes for the APY displayed in the vesting page)
> 
> So far, code looks correct based on Chris' computation.
> 
> ![image](https://user-images.githubusercontent.com/6169194/120986940-ad8f8380-c7af-11eb-9186-cbfe10b37e93.png)

Okay on it @tracyarciaga

2021-06-07 10:46 UTC, chris247474 commented on src/components/Farm/FarmPoolCard.tsx
> +  const monthlyAPY = rewardMonthUSDValue / poolLiquidity;
@barryhalo sounds good

2021-06-07 10:48 UTC, barryhalo commented
@tracyarciaga APY comma has been fixed

<img width="884" alt="Screen Shot 2021-06-07 at 6 40 25 PM" src="https://user-images.githubusercontent.com/81855319/121004004-bd639380-c7c0-11eb-873e-beb7febc9b1a.png">

@schystz 
Added HALO token in `COINGECKO_KNOWN_TOKENS`

2021-06-07 10:57 UTC, chris247474 requested changes
@barryhalo equation seems to make sense (that's all i checked, @schystz would be a better check on the rest of the code :) ). Just left a comment on putting the logic in a helper file. 

Is the unit test for the APY calculation in this PR as well, sorry if i missed that

2021-06-07 10:57 UTC, chris247474 commented on src/components/Farm/FarmPoolCard.tsx
> +  const monthlyReward = rewardTokenPerSecond ? 30 * 24 * 60 * 60 * rewardTokenPerSecond : 0
@barryhalo looks great! thoughts on putting this in a helper func? that way any unit tests can just import it and test against it.

2021-06-07 10:59 UTC, barryhalo commented on src/components/Farm/FarmPoolCard.tsx
> +  const monthlyReward = rewardTokenPerSecond ? 30 * 24 * 60 * 60 * rewardTokenPerSecond : 0
Yeah good catch, on it!

2021-06-07 11:00 UTC, barryhalo commented on src/components/Farm/FarmPoolCard.tsx
> +  const monthlyReward = rewardTokenPerSecond ? 30 * 24 * 60 * 60 * rewardTokenPerSecond : 0
Ahh you mean the whole APY computation, got it!

2021-06-07 11:06 UTC, barryhalo commented on src/components/Farm/FarmPoolCard.tsx
> +  const monthlyReward = rewardTokenPerSecond ? 30 * 24 * 60 * 60 * rewardTokenPerSecond : 0
@ctverceles I didn't include the unit tests here, created a new task for that
https://halodao.atlassian.net/browse/HDF-305

2021-06-07 11:26 UTC, barryhalo commented on src/components/Farm/FarmPoolCard.tsx
> +  const monthlyReward = rewardTokenPerSecond ? 30 * 24 * 60 * 60 * rewardTokenPerSecond : 0
@ctverceles I guess I can include the unit tests here, and just link its Jira issue :)

2021-06-07 14:16 UTC, ernestpascual requested changes
added with some comments. also noticed there's a bunch of eslint things here as well

2021-06-07 14:16 UTC, ernestpascual commented on src/components/Farm/FarmPoolCard.tsx
> +  const HALOToken = process.env.REACT_APP_HALO_REWARDS_ADDRESS_KOVAN
i think we can use the `HALO_TOKEN_ADDRESS` here from `src/constants/index` this should change the address during network changes. This applies to halohalo and reward addresses as well

2021-06-07 14:16 UTC, ernestpascual commented on src/components/Farm/FarmPoolCard.tsx
> +  const monthlyReward = rewardTokenPerSecond ? 30 * 24 * 60 * 60 * rewardTokenPerSecond : 0
We can also use a custom hook actually here

2021-06-07 14:16 UTC, ernestpascual commented on src/constants/index.ts
> +const HALOToken = process.env.REACT_APP_HALO_REWARDS_ADDRESS_KOVAN
For this i think u can use line 104 instead?

2021-06-08 10:40 UTC, barryhalo commented on src/components/Farm/FarmPoolCard.tsx
> +  const HALOToken = process.env.REACT_APP_HALO_REWARDS_ADDRESS_KOVAN
> i think we can use the `HALO_TOKEN_ADDRESS` here from `src/constants/index` this should change the address during network changes. This applies to halohalo and reward addresses as well

@ernestpascual 

Resolved

2021-06-08 10:41 UTC, barryhalo commented on src/constants/index.ts
> +const HALOToken = process.env.REACT_APP_HALO_REWARDS_ADDRESS_KOVAN
> For this i think u can use line 104 instead?

@ernestpascual 

Resolved

2021-06-08 11:20 UTC, barryhalo commented
@ernestpascual @schystz 

APY hook is ready for review

2021-06-09 11:22 UTC, schystz commented
Closing this PR to submit a fresh one. It looks like GH is a little lost as this PR is showing 29 files changed while if you try to open a new PR for the same changes (https://github.com/HaloDAO/halodao-interface/compare/develop...feature/hdf-13-apy) there are only 9 files changed.

2021-06-09 11:22 UTC, closed without merging