Features/hdev 264 UI for handling errors and warnings
HaloDAO/halodao-interface pull request #154
Opened 2022-02-14 04:06 UTC by psalm-ov

## Description of Changes

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDEV-264)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
* [ ] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [x] I have successfully ran tests locally

2022-02-28 05:50 UTC, 0xAplki requested changes
Do we have specific test txns to evoke the errors (@schystz  @tracyarciaga)? There are conflicting files as well

2022-02-28 05:50 UTC, 0xAplki commented on public/locales/en.json
> +  "SubtractionOverflowErrorMessage": "Overflow Issue",
```suggestion
  "SubtractionOverflowErrorMessage": "Something went wrong. Please show this error message to the team. (Subtraction Overflow)",
```

2022-02-28 05:50 UTC, 0xAplki commented on public/locales/en.json
> +  "MetamaskRejectionErrorMessage": "Metamask Rejection"
```suggestion
  "MetamaskRejectionErrorMessage": "User rejected transaction."
```

2022-02-28 05:50 UTC, 0xAplki commented on src/components/Tailwind/ErrorContent/InlineErrorContent.tsx
> +// TODO: Tailwind?
still need todo?

2022-02-28 05:50 UTC, 0xAplki commented on src/components/Tailwind/ErrorContent/TransactionErrorContent.tsx
> +// TODO: Tailwind?
same here

2022-02-28 05:50 UTC, 0xAplki commented on src/halo-hooks/amm/useSwapToken.ts
> +        // setButtonState(SwapButtonState.InsufficientLiquidity)
eslint here

2022-02-28 05:50 UTC, 0xAplki commented on src/halo-hooks/amm/useSwapToken.ts
>      },
eslint here

2022-03-03 05:27 UTC, schystz commented on public/locales/en.json
> +  "SubtractionOverflowErrorMessage": "Overflow Issue",
@0xAplki one idea here actually is to have an expandable area on the error modal (somewhere at the bottom) that contains the full error log, then a copy a button for the user to easily copy and send it to us devs/support for debugging. So I suggest keeping the default displayed error message simple.

2022-03-03 05:54 UTC, schystz reviewed
Few comments regarding the UI components.

Please also note that moving forward, let's avoid styled components as they tends to make the code bloated and more complicated. Instead let's use tailwind classes to style our components.

2022-03-03 05:54 UTC, schystz commented on src/components/Tailwind/ErrorContent/InlineErrorContent.tsx
> +const Wrapper = styled.div`
Can we avoid using styled components and stick with using tailwind classes instead?

2022-03-03 05:54 UTC, schystz commented on src/components/Tailwind/ErrorContent/TransactionErrorContent.tsx
> +const RetryTransactionLink = styled.button`
Can we avoid using styled components and stick with using tailwind classes instead?

2022-03-03 05:54 UTC, schystz commented on src/constants/tokenLists/halo-tokenlist.ts
> +  [TokenSymbol.fxAUD]: ZERO_ADDRESS,
Pls use `ethers.constants.AddressZero` instead

2022-03-03 05:54 UTC, schystz commented on src/halo-hooks/amm/useSwapToken.ts
> +          Date.now() + 1
Is this a temp code? Can we revert to the correct value for `deadline`?

2022-03-09 10:30 UTC, schystz reviewed
@tracyarciaga please see below comments after reviewing https://github.com/HaloDAO/halodao-interface/pull/157 too

2022-03-09 10:30 UTC, schystz commented on src/components/Tailwind/ErrorContent/TransactionErrorContent.tsx
> +          Retry Transaction
@tracyarciaga thoughts on renaming this to "Dismiss"? I first thought clicking this button will automatically retry the transaction but it looks like it is simply dismissing the modal.

2022-03-09 10:30 UTC, schystz commented on src/components/Tailwind/ErrorContent/TransactionErrorContent.tsx
> +  closeError: () => void
Shall we rename to `onDismiss` for better context?

2022-03-09 10:30 UTC, schystz commented on src/components/Tailwind/ErrorContent/TransactionErrorContent.tsx
> +  objectError: ErrorMessageObject
Instead of having to parse `objectError` & `message` on every parent component, how about we just pass the failing tx in this component - then this component will be responsible on parsing `objectError` & `message` from the tx? This way the logic is centralized in this component and the parent components won't need to have additional logic on error handling.

2022-03-09 10:30 UTC, schystz commented on src/components/Tailwind/ErrorContent/InlineErrorContent.tsx
> +        {message} Please show this error message <span className="text-primary-red">{errorObject.message} </span>
Some tweaks to differentiate errors from the static text

```suggestion
        {message}. Please show this error message: "<span className="text-primary-red">{errorObject.message} </span>"
```

2022-03-09 12:27 UTC, schystz commented on src/components/Tailwind/ErrorContent/TransactionErrorContent.tsx
> +  objectError: ErrorMessageObject
Do note though that we might wanna also want to pass a generic `Error` object here instead of a failing transaction all the time - for run time errors thrown by the app or one of the libraries we are using.

2022-03-10 01:09 UTC, tracyarciaga commented on src/components/Tailwind/ErrorContent/TransactionErrorContent.tsx
> +  objectError: ErrorMessageObject
good point. Agree! @schystz

2022-03-10 03:30 UTC, 0xAplki commented on src/components/Tailwind/ErrorContent/InlineErrorContent.tsx
>      <div className="bg-error-light border-solid border-1 border-error-dark rounded">
just one eslint here

2022-03-10 13:48 UTC, merged