Added max button on stake & unstake field + show HALO amount to claim
HaloDAO/halodao-interface pull request #16
Opened 2021-06-07 03:10 UTC by schystz

## Description of Changes
- Added max button on stake & unstake field on Farm page
- Show HALO amount to claim on Vesting page

UI tweaks:
- Updated copy on reward pink banner under stake/unstake field
- Updated bunny image on Harvest modal (bunny holding RNBW token)
- Implemented max button hover state

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-299)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
* [x] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [x] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

2021-06-07 11:02 UTC, schystz commented on public/locales/en.json
> +  "poolSummaryHaloEarned": "Unclaimed RNBW Earned",
@tracyarciaga any particular reason you changed this to RNBW? The unclaimed HALO we displayed on UI is converted to HALO actually (using the formula `unclaimedRNBW * currentHaloHaloPrice()`)

2021-06-09 02:35 UTC, tracyarciaga commented on public/locales/en.json
> +  "poolSummaryHaloEarned": "Unclaimed RNBW Earned",
ahh token names and symbol have been renamed - we're not using the name HALO anymore.

2021-06-09 02:37 UTC, schystz commented on public/locales/en.json
> +  "poolSummaryHaloEarned": "Unclaimed RNBW Earned",
Ok I see...do we wanna address that in this PR too? I think there are some more places we need to replace not just here.

2021-06-09 02:39 UTC, tracyarciaga commented on public/locales/en.json
> +  "poolSummaryHaloEarned": "Unclaimed RNBW Earned",
Yeah let's do it on another PR, sorry :) will approve this now

2021-06-09 02:39 UTC, tracyarciaga approved these changes
Approving test. I have tested it on my local and preview.

2021-06-09 02:43 UTC, schystz commented on public/locales/en.json
> +  "poolSummaryHaloEarned": "Unclaimed RNBW Earned",
No worries, just wanted to understand about this change to make sure there isn't any confusion. Thanks!

2021-06-09 02:55 UTC, bitcoinbrisbane requested changes
LGTM once the few unused vars are removed.

2021-06-09 03:04 UTC, schystz commented
> LGTM once the few unused vars are removed.

Thanks for the catch @bitcoinbrisbane ! I didn't noticed it until you pointed it out. Fixed now!

2021-06-09 03:08 UTC, bitcoinbrisbane approved these changes

2021-06-09 03:19 UTC, merged