HDF-275
HaloDAO/halodao-interface pull request #22
Opened 2021-06-13 11:09 UTC by tracyarciaga

## Description of Changes
Implemented Empty State UI when user is not connected to a wallet.
1. Add EmptyState component.
2. Add FarmPoolTable component.

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-275)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
* [ ] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

### How to Test:
1. Go to the preview link.
2. Disconnect from metamask.
3. In Farm page and Vesting page, the EmptyState  should be displayed. Refer to [figma](https://www.figma.com/file/lqpLD77mM2olJNrFzuD4Ul?node-id=1760:11#87095201) for the design.

2021-06-16 11:00 UTC, bitcoinbrisbane commented on public/locales/en.json
> +  "emptyStateSubTitleInFarm": "Your one step away from earning. Connect your wallet to join the farm.",
```suggestion
  "emptyStateSubTitleInFarm": "You’re one step away from earning. Connect your wallet to join the farm.",
```

2021-06-16 11:01 UTC, bitcoinbrisbane commented on public/locales/en.json
> +  "emptyStateSubTitleInVest": "Your one step away from earning. Connect your wallet to start to vest."
```suggestion
  "emptyStateSubTitleInVest": "You’re one step away from earning. Connect your wallet to start to vest."
```

2021-06-16 11:06 UTC, bitcoinbrisbane requested changes
Some suggestions and grammar errors

2021-06-16 11:06 UTC, bitcoinbrisbane commented on src/components/EmptyState/index.tsx
> +      if (option.connector === injected) {
Can we use a switch?

2021-06-16 11:06 UTC, bitcoinbrisbane commented on src/pages/HaloHalo/index.tsx
> +  const { t } = useTranslation()
Can we name this guy better?

2021-06-18 03:34 UTC, bitcoinbrisbane approved these changes

2021-06-18 10:28 UTC, tracyarciaga commented on src/pages/HaloHalo/index.tsx
> +  const { t } = useTranslation()
@bitcoinbrisbane actually we can't t is the exported name from useTranslation hook.

2021-06-18 12:20 UTC, schystz reviewed
Hi @tracyarciaga , good work here! UI looks good and the feature works!

Just a few comments below and 3 other things I noticed:

- Can we fix the ESLint errors & warnings? (preview url should generate once this is fixed)

- When I select Fortmatic, there is a considerable delay before the connect modal pops up, and in that time period it looks like the app is frozen

- When I select Portis, nothing seems to happen

2021-06-18 12:20 UTC, schystz commented on src/components/EmptyState/Option.tsx
> +        <img style={{ marginBottom: '0.5rem' }} width={'44px'} src={icon} alt="logo" />
@tracyarciaga shall we use the same image height (instead of width) so that the subheader and body below the image aligns vertically with the other option cards?

<img width="729" alt="Screen Shot 2021-06-18 at 8 03 13 PM" src="https://user-images.githubusercontent.com/1032707/122558189-612a2a80-d070-11eb-80de-b69059340b7f.png">

2021-06-18 12:20 UTC, schystz commented on src/components/EmptyState/Option.tsx
> +          style={{
I would avoid inline styles and stick to styled components whenever possible

2021-06-18 12:20 UTC, schystz commented on src/components/EmptyState/Option.tsx
> +            marginTop: '0.1rem',
I would avoid inline styles and stick to styled components whenever possible

2021-06-18 12:20 UTC, schystz commented on src/components/EmptyState/Option.tsx
> +export default function Option({
Can we stick with es6 arrow function syntax for consistency?

2021-06-18 12:20 UTC, schystz commented on src/components/EmptyState/index.tsx
> +  function Web2Status() {
Can we stick with es6 arrow function syntax for consistency?

2021-06-18 12:20 UTC, schystz commented on src/components/EmptyState/index.tsx
> +  function getOptions() {
Can we stick with es6 arrow function syntax for consistency?

2021-06-18 12:20 UTC, schystz commented on src/pages/Farm/FarmPoolTable.tsx
> +import React from 'react'
Oh, good idea to separate this as a new component @tracyarciaga !

But perhaps we can place it inside `src/components/Farm/` where other farm components reside atm?

2021-06-23 05:36 UTC, schystz reviewed
Minor comments

2021-06-23 05:36 UTC, schystz commented on src/components/EmptyState/index.tsx
> +  // function getOptions() {
Can we remove this line?

2021-06-23 05:36 UTC, schystz commented on src/theme/index.tsx
> +  emptyStateSubHeader(props: TextProps) {
Shall we use a styled component for this under EmptyState component instead of a global one? Seems to be not used anywhere else. Ideally margins and alignment are placed on component not on theme level.

2021-06-23 05:36 UTC, schystz commented on src/components/EmptyState/Option.tsx
> +import { Text } from 'rebass'
Can we fix this warning?

> src/components/EmptyState/Option.tsx#L8
'Text' is defined but never used (@typescript-eslint/no-unused-vars)

2021-06-25 04:47 UTC, schystz commented on src/components/EmptyState/index.tsx
> +          <WalletRow>{getOptions()}</WalletRow>
@tracyarciaga it looks like this is the reason for the eslint error reported on Conversation tab (it wasn't clear there but I found this after going to Files changed tab)

2021-06-28 12:28 UTC, schystz approved these changes
LGTM

2021-06-28 12:53 UTC, merged