hdev-83-implement-bridge-ui-design
HaloDAO/halodao-interface pull request #54
Opened 2021-08-01 17:44 UTC by tracyarciaga

## Description of Changes
Implementation of Bridge UI design using Tailwind CSS

[Link to Jira Ticket HDEV-83](https://halodao.atlassian.net/browse/HDEV-83)
[Link to Jira Ticket HDEV-122](https://halodao.atlassian.net/browse/HDEV-122)
[Link to Jira Ticket HDEV-115](https://halodao.atlassian.net/browse/HDEV-115)

***Not Included in this PR***
-Dynamic population of token list in Token Modal -> this will be covered in Brent's PR 
-Search in Token Modal-> will be included in Brent's PR

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
* [x] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

2021-08-11 13:19 UTC, mystbrent commented on src/pages/Tailwind/Bridge/ButtonGroup.tsx
> +import React, { useState } from 'react'
As discussed should we remove this file and move ButtonGroup component inside bridge?

2021-08-11 14:47 UTC, mystbrent approved these changes
Thank you for pushing @tracyarciaga

Just minor comments on the linting. Aside from that I've rebased from this branch and there were little merge conflicts that I will be resolving in my end.

Everything looks good for me! 👍

2021-08-12 02:06 UTC, bitcoinbrisbane commented on cypress/integration/vesting.test.ts
> +describe.skip('Vesting', () => {
Should we remove?

2021-08-12 02:07 UTC, bitcoinbrisbane commented on cypress/support/commands.js
> +const PRIVATE_KEY_TEST_NEVER_USE = '0x8b7e0e7111e2896c6767c21534dddaedd28b63903a2e1c5be723e89d253f2f04'
Should we just put in a `.env` file to be sure?

2021-08-12 02:08 UTC, bitcoinbrisbane commented on cypress/support/commands.js
> +      const provider = new JsonRpcProvider('https://kovan.infura.io/v3/e635823b24d2499982b765aad53cb5c6', 42)
Some with this?  @ctverceles maybe we standardise our .env names too?

2021-08-12 02:19 UTC, bitcoinbrisbane commented on src/components/Slider/index.tsx
> +      // style={{ width: '90%', marginLeft: 15, marginRight: 15, padding: '15px 0' }}
Should we just remove?

2021-08-12 02:27 UTC, bitcoinbrisbane commented on cypress/integration/farm.test.ts
> +describe.skip('Farm', () => {
Is this intended?

2021-08-12 02:27 UTC, bitcoinbrisbane commented on cypress/integration/landing.test.ts
> +  it.skip('is connected', () => {
Is this intended?

2021-08-12 02:37 UTC, bitcoinbrisbane commented on src/components/Tailwind/Modals/NetworkModal.tsx
> +            //ChainId.MOONBASE
Should we remove?

2021-08-12 03:10 UTC, bitcoinbrisbane commented on src/constants/lists.ts
> +// const QUICK_SWAP = 'https://unpkg.com/quickswap-default-token-list@1.0.39/build/quickswap-default.tokenlist.json'
Should re remove?

2021-08-12 03:11 UTC, bitcoinbrisbane commented on src/halo-hooks/useHaloHalo.ts
> +    const apy = Number(Fraction.from(bal, supply).toString()) * 12
Should this be 0.12 ?

2021-08-12 03:12 UTC, bitcoinbrisbane commented on src/pages/Tailwind/Bridge/ButtonGroup.tsx
> +    }
Could we do this as a switch?

2021-08-12 03:14 UTC, bitcoinbrisbane commented on src/pages/Tailwind/Bridge/index.tsx
> +    }
And this?

2021-08-12 03:14 UTC, bitcoinbrisbane commented on src/pages/Tailwind/Bridge/modals/BridgeTransactionModal.tsx
> +          <a className="font-semibold text-link" href="https://etherscan.io/" target="_blank" rel="noopener noreferrer">
Do we need a toggle for kovan or similar?

2021-08-12 03:19 UTC, bitcoinbrisbane commented on src/pages/Tailwind/Pool/index.tsx
> +            caption="ERC721 token standard returns a immutable raiden network! VeChain should be a ERC20 token standard!"
is this correct?

2021-08-12 03:23 UTC, bitcoinbrisbane commented on src/pages/Tailwind/Pool/modals/AddLiquityModal.tsx
> +          Swapping <b>0.1 ETH</b> for <b>8.82411 DAI</b>
are these supposed to be constants?

2021-08-12 03:23 UTC, bitcoinbrisbane commented on src/pages/Tailwind/Pool/modals/AddLiquityModal.tsx
> +                <div>1 USDT = 1 XSGD</div>
are these supposed to be constants / static?

2021-08-12 03:23 UTC, bitcoinbrisbane commented on src/pages/Tailwind/Pool/modals/AddLiquityModal.tsx
> +              <div>500 USDT</div>
are these supposed to be constants / static?

2021-08-12 03:23 UTC, bitcoinbrisbane commented on src/pages/Tailwind/Pool/modals/AddLiquityModal.tsx
> +              <div>500 XGSD</div>
are these supposed to be constants / static?

2021-08-12 03:24 UTC, bitcoinbrisbane commented on src/pages/Test/TailwindDemo.tsx
> +              caption="ERC721 token standard returns a immutable raiden network! VeChain should be a ERC20 token standard!"
Is this correct?

2021-08-12 03:25 UTC, bitcoinbrisbane requested changes
Few ideas / suggestions.  Few TS compiler errors

2021-08-12 08:14 UTC, tracyarciaga commented on src/pages/Test/TailwindDemo.tsx
> +              caption="ERC721 token standard returns a immutable raiden network! VeChain should be a ERC20 token standard!"
Ahh this is only demo page.

2021-08-12 08:16 UTC, tracyarciaga commented on src/pages/Tailwind/Pool/modals/AddLiquityModal.tsx
> +          Swapping <b>0.1 ETH</b> for <b>8.82411 DAI</b>
@bitcoinbrisbane sorry for the confusion but yes, it's suppose to be static - because PR's scope is only building UI using tailwind. No contract interactions yet.

2021-08-12 08:17 UTC, tracyarciaga commented on src/pages/Tailwind/Bridge/index.tsx
> +    }
ok

2021-08-12 11:36 UTC, closed without merging