Features/hdf 200 vesting modal
HaloDAO/halodao-interface pull request #6
Opened 2021-05-19 08:32 UTC by schystz

## Description of Changes

- Added Harvest modal on Vesting page
  - shows up after clicking Harvest button from Farm page
  - won't show if simply visiting the Vesting page (click Vesting from main nav)
- On Farm page, renamed `Unclaimed HALO Earned` to `My HALO Earned`

UI tweaks
- Standard border radius of modal screens
- Standard border radius of Halo buttons

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-241)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
* [x] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [x] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

2021-05-21 01:35 UTC, tracyarciaga approved these changes
All changes are good. Approving this.

2021-05-22 07:47 UTC, tracyarciaga commented
@schystz I renamed instances of dessert pool and DSRT to rainbow pool and RNBW, can I just push it in this  PR too?

2021-05-22 07:51 UTC, schystz commented
> All changes are good. Approving this.

Hi @tracyarciaga , do you mind if you push that instead to my working branch `features/hdf-77-harvest-rewards`? I have a feeling that your changes might have some conflicts with what I am doing now...

2021-05-24 03:10 UTC, tracyarciaga commented
> > All changes are good. Approving this.
> 
> Hi @tracyarciaga , do you mind if you push that instead to my working branch `features/hdf-77-harvest-rewards`? I have a feeling that your changes might have some conflicts with what I am doing now...

I will just do a separate PR, cos it needs to be updated before the usability testing with users.  Thanks @schystz

2021-05-24 05:36 UTC, bitcoinbrisbane commented on src/components/VestingModal/index.tsx
> +    earningHALO = poolVestingInfo?.balance.halo ?? 0
Might read better on two lines IMO.

```suggestion
  const earningDSRT = poolVestingInfo?.balance.dsrt ?? 0
  const earningHALO = poolVestingInfo?.balance.halo ?? 0
```

2021-05-24 05:38 UTC, bitcoinbrisbane requested changes
One comment and need to fix the linting issues.

2021-05-24 06:03 UTC, schystz commented on src/components/VestingModal/index.tsx
> +    earningHALO = poolVestingInfo?.balance.halo ?? 0
Good catch. Will fix. Thanks @bitcoinbrisbane !

2021-05-24 06:39 UTC, schystz commented
> One comment and need to fix the linting issues.

Thanks for the feedback @bitcoinbrisbane! Fixed both of them

2021-05-25 13:21 UTC, ernestpascual approved these changes

2021-05-26 03:38 UTC, merged