features/hdev-237-network-not-supported-bridge
HaloDAO/halodao-interface pull request #63
Opened 2021-09-06 10:05 UTC by tracyarciaga

## Description of Changes

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDEV-237)

### Developer Checklist:

* [ ] I have followed the guidelines in our Contributing document
* [ ] This PR has a corresponding JIRA ticket
* [ ] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
* [ ] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

2021-09-06 10:17 UTC, chris247474 approved these changes
works for me @tracyarciaga !!

2021-09-06 10:41 UTC, 0xAplki requested changes
just some eslint stuff otherwise looks good!

2021-09-06 10:41 UTC, 0xAplki commented on src/pages/Tailwind/Bridge/modals/BridgeTransactionModal.tsx
>            <div className="py-4 text-sm">
we can comment out estimatedGas first if we are not using it

2021-09-06 11:00 UTC, mystbrent commented
![image](https://i.imgur.com/qOODI04.png)

Just noticed clicking the tx hash here does not redirect to the deposit tx on chain explorer.

I'll review but I remember this was already developed before in my branch

Edit: I did another transaction but it link was redirecting correctly. I'll comment again here if the error happens again

2021-09-06 11:02 UTC, tracyarciaga commented on src/pages/Tailwind/Bridge/modals/BridgeTransactionModal.tsx
>            <div className="py-4 text-sm">
@0xAplki Done, I just hide the div, instead of commenting out all related codes to it.

2021-09-06 11:09 UTC, mystbrent commented
![image](https://i.imgur.com/5A6JktH.png)

I think we should comment out the expected gas for now since its not yet done

2021-09-06 12:36 UTC, tracyarciaga commented
> ![image](https://camo.githubusercontent.com/8068c9d54fefaf3399a7d7c723602e9f57100ba34e647dd90013ed399e9b1ddb/68747470733a2f2f692e696d6775722e636f6d2f3541364a6b74482e706e67)
> 
> I think we should comment out the expected gas for now since its not yet done

Thanks @mystbrent this is fixed now.

2021-09-06 13:21 UTC, mystbrent approved these changes
Looks good to me well done thank you @tracyarciaga !

2021-09-06 13:50 UTC, 0xAplki approved these changes

2021-09-06 13:50 UTC, 0xAplki commented
oops i think i clicked your approval @mystbrent sorry!

2021-09-06 23:33 UTC, bitcoinbrisbane commented on src/components/Tailwind/Layout/PageNotSupported.tsx
> +const PageNotSupported = ({ caption }: PageNotSupportedProps) => {
What do we mean by page not supported?

2021-09-06 23:34 UTC, bitcoinbrisbane commented on src/pages/Tailwind/Bridge/index.tsx
> +  const caption = 'Ooops! Sorry this page/feature is not supported in ' + NETWORK_LABEL[chainId as ChainId] + '.'
I like templates :)
```suggestion
  const caption = `Ooops! Sorry this page/feature is not supported in ${NETWORK_LABEL[chainId as ChainId]}.`
```

2021-09-06 23:35 UTC, bitcoinbrisbane commented on src/pages/Tailwind/Bridge/index.tsx
> +  return content
Not 100% sure with react, but we could probably reduce complexity here...

```suggestion
  if (features?.bridge) {
    return <BridgePanel />
  }
  return <NotSupportedContent />
```

2021-09-06 23:37 UTC, bitcoinbrisbane reviewed
Few comments and suggestions...

2021-09-07 01:36 UTC, tracyarciaga commented on src/components/Tailwind/Layout/PageNotSupported.tsx
> +const PageNotSupported = ({ caption }: PageNotSupportedProps) => {
Oh, yeah make sense.. I renamed the component now to PageWarning @bitcoinbrisbane

2021-09-07 03:45 UTC, merged