Add UI for empty state for bridge when wallet is not connected
HaloDAO/halodao-interface pull request #65
Opened 2021-09-07 14:16 UTC by barryhalo

## Description of Changes
Add empty state for bridge when wallet is not connected
Display

<img width="1393" alt="Screen Shot 2021-09-07 at 10 15 15 PM" src="https://user-images.githubusercontent.com/81855319/132360103-28a40908-18cb-4e06-8602-89089443a5c0.png">

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDEV-236)

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [x] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDF-XXX-description`
* [x] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [x] Code is readable and understandable; any unclear parts have explanations 
* [x] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

2021-09-07 18:48 UTC, 0xAplki reviewed
Just left a comment. Working when I'm in polygon. Mainnet does not work though. Not sure if this is the desired behavior. I also re-ran the test seems to be passing now :)

2021-09-07 18:48 UTC, 0xAplki commented on src/pages/Tailwind/Bridge/index.tsx
> +  } else if (chainId === 1) {
just checking why we need to check if `chainId` is 1? We still want main net right? Works well in polygon tho based from the deployed link.

2021-09-07 22:28 UTC, schystz commented on src/pages/Tailwind/Bridge/index.tsx
> +  } else if (chainId === 1) {
I think a better condition is `else if (!account)` (add `account` to the destructure vars on line 39)

Currently the connect button always show up when selected network is Ethereum, even though wallet is already connected

2021-09-08 08:14 UTC, chris247474 requested changes
@barryhalo i think needs a bit more testing, doesn't yet detect when the wallet is loaded 

See video here https://halodao-project.slack.com/archives/C025Q3SUE81/p1631088917140800?thread_ts=1631064332.128500&cid=C025Q3SUE81

![image](https://user-images.githubusercontent.com/16344192/132472099-f70cef54-0b83-4668-8977-42ec9de89ccc.png)

2021-09-08 08:14 UTC, chris247474 commented on src/pages/Tailwind/Bridge/index.tsx
> +  const caption = 'Get access to the bridge right connect to you wallet!'
```suggestion
  const caption = 'Connect your wallet to start bridging your tokens!'
```

2021-09-08 13:02 UTC, barryhalo commented
> @barryhalo i think needs a bit more testing, doesn't yet detect when the wallet is loaded
> 
> See video here https://halodao-project.slack.com/archives/C025Q3SUE81/p1631088917140800?thread_ts=1631064332.128500&cid=C025Q3SUE81
> 
> ![image](https://user-images.githubusercontent.com/16344192/132472099-f70cef54-0b83-4668-8977-42ec9de89ccc.png)

@ctverceles fixed now

2021-09-08 13:02 UTC, barryhalo commented
@schystz @0xAplki ready for review

2021-09-08 13:06 UTC, schystz commented on src/pages/Tailwind/Bridge/index.tsx
> +  } else if (account === null) {
@barryhalo `account` can also be undefined, so a simpler condition would be `else if (!account)` which should cover both null & undefined

2021-09-08 21:11 UTC, 0xAplki reviewed
Working for me! tried a variety of switches on other networks as well. Same comment as @schystz on the code but I'll go on and do the first tick. :)

2021-09-08 21:11 UTC, 0xAplki approved these changes

2021-09-09 01:20 UTC, chris247474 commented
All working for me! Re-requested review but consider this a tick (guess its just James' comemnt thats left then we can merge this)!

2021-09-09 02:58 UTC, barryhalo commented on src/pages/Tailwind/Bridge/index.tsx
> +  } else if (account === null) {
@schystz copy!

2021-09-09 03:00 UTC, barryhalo commented
@schystz for review, falsey !account value

2021-09-09 03:03 UTC, schystz approved these changes
Looks good now @barryhalo !

2021-09-09 03:04 UTC, merged