Bugfix: base quote estimated deposit different than user input
HaloDAO/halodao-interface pull request #96
Opened 2021-09-21 07:32 UTC by schystz

**Important Note:
This branch base is from https://github.com/HaloDAO/halodao-interface/pull/94 so please consider checking that PR first before this issue so there are less files here to review.**

https://halodao.atlassian.net/browse/HDB-29

## Description of Changes

Fixed an issue wherein on XSGD/USDC curve wherein upon entering a base amount, the deposit amount returned by `viewDeposit` is different (much larger). This issue also causes the estimated LP amount to be too high so unless user sets a very high slippage (e.g. 50%) the tx will always fail.

### Developer Checklist:

* [x] I have followed the guidelines in our Contributing document
* [ ] This PR has a corresponding JIRA ticket
* [x] My branch conforms with our naming convention i.e. `feature/HDEV-XXX-description`
* [x] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

2021-09-21 11:47 UTC, bitcoinbrisbane approved these changes

2021-09-21 21:58 UTC, barryhalo approved these changes
Looking good!

2021-09-22 08:02 UTC, chris247474 requested changes
@schystz works great on kovan and mainnet! one comment to implement the logic on `previewDepositGivenQuote` as well

2021-09-22 08:02 UTC, chris247474 commented on src/halo-hooks/amm/useAddRemoveLiquidity.ts
>    const previewDepositGivenQuote = useCallback(
@schystz i guess we wanna apply the new logic here as well to account for all scenarios

2021-09-22 08:21 UTC, schystz commented on src/halo-hooks/amm/useAddRemoveLiquidity.ts
>    const previewDepositGivenQuote = useCallback(
Already implemented here @ctverceles , pls see lines 91-108.

I think you might have seen the outdated commit I posted earlier. Added a few more commits after that.

2021-09-23 02:08 UTC, chris247474 commented
Looks good @schystz ! tried on kovan, polygon mainnet pools. estimation in line err shows up as expected when new estimate is very slightly over user input. Re requested review but this is approval

2021-09-23 06:06 UTC, tracyarciaga approved these changes
lgtm

2021-09-23 06:06 UTC, tracyarciaga commented on src/constants/errors.ts
> +export enum ZapErrorCode {
@schystz @0xAplki Maybe we need to consolidate all our errors in one implementation, thoughts?

2021-09-23 06:14 UTC, schystz commented on src/constants/errors.ts
> +export enum ZapErrorCode {
Definitely! I think @0xAplki is working on that already right?

Though to clarify, this file is meant to be a collection of errors returns by web3/contracts though, not the errors we show to the user.

2021-09-23 09:17 UTC, merged